server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql:// 192.168.31.88:3306/wechat?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: wechat
    password: F7BYz34328RXhWmf
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
    database-platform: com.songyuankun.config.MysqlConfig
  redis:
    database: 0
    host: 192.168.31.88
    port: 6379
    password: 123456
  cache:
    type: redis
  session:
    store-type: redis
  jackson:
    time-zone: GMT+8
my:
  wechat:
    appid:
    secret:
    token:
    admin:
      corp_id:
      agent_id:
      secret:

jd:
  app_key:
  secret_key:
  site_id:
  pt_key:
  pt_pin:
  key:
  union_id:
  web_cookie:

taobao:
  app_key:
  secret:
  adzone_id: